---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

## Packages to use ----
pacman::p_load(
  tidyverse, janitor, writexl,
  readxl, scales, mytidyfunctions
)

## Set theme ------
theme_set(theme_jmr(text = element_text(family = "Times New Roman")))

options(
  ggplot2.discrete.colour = c("#277DA1", "#f94144", "#F9C74F", "#43AA8B"),
  ggplot2.discrete.fill = c("#277DA1", "#f94144", "#F9C74F", "#43AA8B")
)
```

##  Regularized Binary Regression Model for Relative Risk

Package version of [ChloeYou/regularized-RR-regression](https://github.com/ChloeYou/regularized-RR-regression). It develops an algorithm that extends on the [`rbrm`](https://github.com/mclements/brm) package to estimate relative risk.

📖 The original model is based on the [regularized binary regression model](https://arxiv.org/abs/1510.02430) (rbrm) paper by Thomas S. Richardson, James M. Robins, Linbo Wang.

#### Installation

You can install the development version from 
[GitHub](https://github.com/JavierMtzRdz/rbrm) with

``` r
remotes::install_github("JavierMtzRdz/rbrm")
# Or
devtools::install_github("JavierMtzRdz/rbrm")	
```

#### 📂 This repository contains the following files

* `rbrm.r`: contains the R function for the algorithm
* `cv.rbrm.r`: contains the R function for performing cross-validation
* `helper.r`: contains some helper functions

#### 💡 Abstract

Binary regression models, such as Poisson and logistic regression, are commonly employed in clinical studies to estimate measures like relative risks (RR) or odds ratios (OR). While RR are preferred for their straightforward interpretation, logistic regression, which models OR, is the most widely used approach. However, it only provides a reliable estimate of RR when the outcome of interest is infrequent. Meanwhile, the Poisson regression can estimate RR directly but can produce fitted probabilities outside the range of zero and one. To address these challenges, Richardson et al. (2017) proposed a novel binary regression model that estimates RR directly via a log odds-product nuisance model. However, this model also has limitations in estimating high-dimensional data (p > N). Therefore, we propose a new estimator and develop an algorithm of the binary regression model that allows variable selection when p > N. Finally, we examine the properties of our estimator in a simulation study.
